-- AlterTable
ALTER TABLE `Comments` ADD COLUMN `totalAngry` INTEGER NULL DEFAULT 0,
    ADD COLUMN `totalLikes` INTEGER NULL DEFAULT 0,
    ADD COLUMN `totalLove` INTEGER NULL DEFAULT 0,
    ADD COLUMN `totalSad` INTEGER NULL DEFAULT 0,
    ADD COLUMN `totalWoW` INTEGER NULL DEFAULT 0;
